on: push
name: Unit tests
jobs:
  checks:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run
        uses: cedrickring/golang-action/go1.14@1.5.2
        with:
          args: make test
